name: Customer API CI/CD

on:
  pull_request:
    branches:
      - main
    paths:
        - 'src/**'
        - 'Dockerfile'
        - 'ecs-parameters.yaml'
        - '.github/workflows/deploy.yaml'

  push:
    branches:
      - main
    paths:
          - 'src/**'
          - 'Dockerfile'
          - 'ecs-parameters.yaml'
          - '.github/workflows/deploy.yaml'

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-1

jobs:
  pre-build:
    uses: SparrowX-ECS/workflows-templates/.github/workflows/pre-build.yaml@v3.1.0

  test:
    name: Test
    needs: pre-build
    if: needs.pre-build.outputs.build-needed == 'true'
    uses: SparrowX-ECS/workflows-templates/.github/workflows/test.yaml@v3.1.0
    with:
      runtime: python
      database: true

  build:
    needs: [pre-build, test]
    if: |
        needs.test.result == 'success' &&
        github.event_name == 'push' &&
        github.ref == 'refs/heads/main' &&
        needs.pre-build.outputs.build-needed == 'true'
    uses: SparrowX-ECS/workflows-templates/.github/workflows/build.yaml@v3.1.0

  deploy:
    needs: [pre-build, build]
    if: |
      always() &&
      needs.pre-build.outputs.deploy-needed == 'true' &&
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      (needs.build.result == 'success' || needs.build.result == 'skipped')
    uses: SparrowX-ECS/workflows-templates/.github/workflows/deploy.yaml@v3.1.0
    with:
      database-enabled: true
      update-image: ${{ needs.build.result == 'success' }}